/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids2425.filieraagricolalocale;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
